#!/usr/bin/env python3
"""Build 1 Enoch chapters 1-12 Ge'ez + English JSON."""
import json, os

D={}
def ch(n,t): D[str(n)]={"title":t,"verses":{}}
def vs(c,n,g,e): D[str(c)]["verses"][str(n)]={"geez":g,"english":e}

# Chapter 1 (9 verses)
ch(1,"Chapter 1")
vs(1,1,"ቃለ፡ በረከት፡ ዘሄኖክ፡ ዘከመ፡ ባረከ፡ ኍሩያነ፡ ወጻድቃነ፡ እለ፡ ሀለው፡ ይኩኑ፡ በዕለተ፡ ምንዳቤ፡ ለአሰስሎ፡ ኵሎ፡ እኩያን፡ ወረሲዓን።","The words of the blessing of Enoch, wherewith he blessed the elect and righteous, who will be living in the day of tribulation, when all the wicked and godless are to be removed.")
vs(1,2,"ወአውሥአ፡ ሄኖክ፡ ወይቤ፡ ብእሲ፡ ጻድቅ፡ ዘእምኋበ፡ እግዚአብሔር፡ እንዘ፡ አዕይንቲሁ፡ ክሡታት፡ ወይሬኢ፡ ራእየ፡ ቅዱሰ፡ ዘበሰማያት፡ ዘአርአዩኒ፡ መላእክት፡ ወሰማዕኩ፡ እምኋቤሆሙ፡ ኵሎ፡ ወአእመርኩ፡ አነ፡ ዘእሬኢ፡ ወአኮ፡ ለዝ፡ ትውልድ፡ አላ፡ ለትውልድ፡ ርሑቅ፡ ዘይመጽእ።","And Enoch a righteous man, whose eyes were opened by God, saw the vision of the Holy One in the heavens, which the angels showed me, and from them I heard everything, and from them I understood as I saw, but not for this generation, but for a remote one which is for to come.")
vs(1,3,"በእንተ፡ ኍሩያን፡ እቤ፡ ወአውሣእኩ፡ በእንቲአሆሙ፡ ምስለ፡ ዘቅዱስ፡ ወዐቢይ፡ ይወጽእ፡ እምነ፡ መኋድሪሁ።","Concerning the elect I said, and took up my parable concerning them: The Holy Great One will come forth from His dwelling.")
vs(1,4,"ወእምህ፡ ይረግዝ፡ ዲበ፡ ደብረ፡ ሲና፡ ወይትራአይ፡ በጽንዐ፡ ኋይሉ፡ እምሰማይ፡ ሰማያት።","And the God of the world will tread upon Mount Sinai and appear in the strength of His might from the heaven of heavens.")
vs(1,5,"ወይፈርሁ፡ ኵሎሙ፡ ወያአምኑ፡ ዐቃብያን፡ ወይርዐዱ፡ ወይፌዝወም፡ ፍርሃት፡ ዐቢይ፡ እስከ፡ አጽናፈ፡ ምድር።","And all shall be smitten with fear and the Watchers shall quake, and great fear and trembling shall seize them unto the ends of the earth.")
vs(1,6,"ወይትናዘዑ፡ አድባረ፡ ልዑላን፡ ወይትሐቱ፡ ኵርባኔ፡ ልዑላን፡ ወይትመዐው፡ ከመ፡ ሰአሊ፡ ቅድመ፡ እሳት፡ ወከመ፡ ማይ፡ ዘይወርድ፡ በኅላኅል።","And the high mountains shall be shaken, and the high hills shall be made low, and shall melt like wax before the flame.")
vs(1,7,"ወትትነጠቅ፡ ምድር፡ በመሰንቆ፡ ወኵሉ፡ ዘዲቤሃ፡ ይጠፍእ፡ ወይከውን፡ ደይን፡ ዲበ፡ ኵሉ።","And the earth shall be wholly rent in sunder, and all that is upon the earth shall perish, and there shall be a judgement upon all.")
vs(1,8,"ወምስለ፡ ጻድቃን፡ ይገብር፡ ሰላመ፡ ወዲበ፡ ኍሩያን፡ ይኩን፡ ዕቀባ፡ ወኋልይዮት፡ ወይኩኖሙ፡ ኵሎሙ፡ ዘእግዚአብሔር፡ ወይሠምሮሙ፡ ወይባርኮሙ፡ ወብርሃን፡ እግዚአብሔር፡ ያበርህ፡ ሎሙ።","But with the righteous He will make peace and will protect the elect, and mercy shall be upon them. And they shall all belong to God, and they shall be prospered, and they shall all be blessed. And He will help them all, and light shall appear unto them, and He will make peace with them.")
vs(1,9,"ወናሁ፡ ይመጽእ፡ ምስለ፡ እልፍ፡ ቅዱሳን፡ ወመላእክቲሁ፡ ለገቢረ፡ ደይን፡ ዲበ፡ ኵሉ፡ ወያጠፍእ፡ ኵሎ፡ ረሲዓን፡ ወይ኎ጽር፡ ኵሎ፡ ዘሥጋ፡ በእንተ፡ ኵሉ፡ ዘገብሩ፡ ወዐመጱ፡ ዲቤሁ፡ ኋጥኣን፡ ወረሲዓን።","And behold! He cometh with ten thousands of His holy ones to execute judgement upon all, and to destroy all the ungodly, and to convict all flesh of all the works of their ungodliness which they have ungodly committed, and of all the hard things which ungodly sinners have spoken against Him.")

# Chapter 2 (3 verses)
ch(2,"Chapter 2")
vs(2,1,"ቢዘ፡ እክይአት፡ እመክርኩ፡ ቅዱሳነ፡ እግዚአብሔር፡ እመክነይኩ፡ በእንተ፡ ግብርኩሙ፡ ዘኵሎሙ፡ ዲቤ፡ ምድር።","Observe ye everything that takes place in the heaven, how they do not change their orbits, and the luminaries which are in the heaven, how they all rise and set in order each in its season, and transgress not against their appointed order.")
vs(2,2,"ቢዘ፡ ምድረ፡ ወብዘው፡ ዕዐኑ፡ ዘዲቤሃ፡ ወእምእፅዋኘ፡ እግዚአብሔር፡ እመክኘይ፡ አለ፡ እምእፅዋኘ፡ እግዚአብሔር፡ ዲያብሎስ፡ ምድር፡ ወይመርቅ፡ ዕዐው።","Behold ye the earth, and give heed to the things which take place upon it from first to last, how steadfast they are, how none of the things upon earth change, but all the works of God appear to you.")
vs(2,3,"ቢዘ፡ ከውጂ፡ ወበሠጋ፡ እመክንይኩ፡ በእንተ፡ መክራኑ፡ ዘእግዚአብሔር፡ ወመክንይኩ፡ ዘእፅዋኔ፡ እግዚአብሔር፡ እመክኖ፡ እምይደወስ፡ ወእምይኪደ፡ በእንተው።","Behold the summer and the winter, how the whole earth is filled with water, and clouds and dew and rain lie upon it.")

# Chapter 3 (1 verse)
ch(3,"Chapter 3")
vs(3,1,"ቢዘ፡ ወእመክንይኩ፡ እመክንይ፡ እፅዋነ፡ እግዚአብሔር፡ እምእፍዕው፡ ገባሪ፡ ዘኵሎሙ፡ እምይኪደ፡ በእንተው፡ ወእመክንይ፡ እፅዋነ፡ እግዚአብሔር፡ በኵሉ፡ እምይሰዐር፡ እንተ፡ይዘውእ።","Observe and see how in the winter all the trees seem as though they had withered and shed all their leaves, except fourteen trees, which do not lose their foliage but retain the old foliage from two to three years till the new comes.")

# Chapter 4 (1 verse)
ch(4,"Chapter 4")
vs(4,1,"ወካዕ፡ ቢዘ፡ እምእፅዋነ፡ እግዚአብሔር፡ በእንተ፡ መካን፡ ዘከውጂ፡ እመክንይ፡ እፅዋነ፡ እግዚአብሔር፡ ወእምእፅዋነ፡ እግዚአብሔር፡ በእንተ፡ ዐዓዊያን፡ እምይፈርዩ፡ ወእምይካዕ።","And again, observe ye the days of summer how the sun is above the earth over against it. And you seek shade and shelter by reason of the heat of the sun, and the earth also burns with growing heat, and so you cannot tread on the earth, or on a rock by reason of its heat.")

# Chapter 5 (9 verses)
ch(5,"Chapter 5")
vs(5,1,"ቢዘ፡ እምእፅዋነ፡ እግዚአብሔር፡ እመክንይ፡ እፍዕው፡ ዕዐኑ፡ በእንተ፡ ከውጂ፡ ወበሠጋ፡ እመክንይኩ፡ ዘዲቤ፡ምድር።","Observe ye how the trees cover themselves with green leaves and bear fruit: wherefore give ye heed and know with regard to all His works, and recognize how He that liveth for ever hath made them so.")
vs(5,2,"ወእፅዋነ፡ እግዚአብሔር፡ እምይደወስ፡ ወእምይኪደ፡ በእንተው፡ ወበእንተው፡ እምእፅዋነ፡ እግዚአብሔር፡ ይገብር፡ ለእግዚአብሔር፡ ኵሎ፡ ምዕራበ፡ ወኵሎ፡ ግብርኩሙ፡ እምይኪደ፡ በእንተው።","And all His works go on thus from year to year for ever, and all the tasks which they accomplish for Him, and their tasks change not, but according as God hath ordained so is it done.")
vs(5,3,"ወቢዘ፡ እምእፅዋነ፡ እግዚአብሔር፡ እምያም፡ ወእምባሕር፡ እምይመልእ፡ በእንተው፡ ወእምይኪደ፡ በእንተው።","And behold how the sea and the rivers in like manner accomplish and change not their tasks from His commandments.")
vs(5,4,"ወአንትሙ፡ እይጠይቅኩ፡ ወእይግበርኩ፡ እፅዋነ፡ እግዚአብሔር፡ ወእይኪድኩ፡ በቅድሱ፡ አላ፡ አክደርኩ፡ ወአክገበርኩ፡ እፅዋኔ፡ እግዚአብሔር።","But ye - ye have not been steadfast, nor done the commandments of the Lord, but ye have turned away and spoken proud and hard words with your impure mouths against His greatness.")
vs(5,5,"ዮ፡ እኩያን፡ እልበኩሙ፡ እምገብርኩ፡ ሰላመ፡ ወእምግብርኩ፡ ስብሀተ፡ እልበኩሙ።","Oh, ye hard-hearted, ye shall find no peace.")
vs(5,6,"ወበእንተዘ፡ ትረግም፡ መካንኩሙ፡ ወትኩን፡ ደይን፡ ወምክንይት፡ ዐቢይ፡ ዲቤኩሙ።","And therefore shall ye execrate your days, and the years of your life shall perish, and the years of your destruction shall be multiplied in eternal execration.")
vs(5,7,"ወእምይትረፍ፡ ለኩሙ፡ ኵሎ፡ ፈፃው፡ አላ፡ ኍሩያን፡ ይወርሱ፡ ዥድመአ፡ ወዥድመአ፡ ወይእረፍ፡ እምአውዓሎም።","And there shall be no mercy and no peace for you.")
vs(5,8,"ወበእንተዘ፡ ኍሩያን፡ ይከውን፡ በሰላም፡ ወይኩኖሙ፡ በርሃን፡ ወስብሀት፡ ወእምዕባቤ፡ ይዐቢይ፡ ወሐገ፡ እግዚአብሔር፡ ይወርድ፡ ዲቤሆሙ።","And in those days the elect shall possess light, joy, and peace, and they shall inherit the earth. And then there shall be bestowed upon the elect wisdom, and they shall all live.")
vs(5,9,"ወእምይካዕ፡ ይገብሩ፡ ኋጥኣት፡ ወእምይምሥዑ፡ ለኋጥኣት፡ ወበኵሎ፡ መካን፡ እምቨሙ፡ ይከብርኩ፡ ወእምይምጥእኩ፡ ዥድመአ።","And they shall not again sin, and they shall not die of the divine anger, but they shall complete the number of the days of their life.")

# Chapter 6 (8 verses)
ch(6,"Chapter 6")
vs(6,1,"ወከም፡ በዘሁ፡ ወለዱ፡ ደቅደቅኩ፡ አውላደ፡ ምድር፡ ረእዩ፡ አዋልድ፡ ዘሰብእ፡ እመ፡ ጵዑዋነ፡ ወሐዎ፡ ሎሙ።","And it came to pass when the children of men had multiplied that in those days were born unto them beautiful and comely daughters.")
vs(6,2,"ወረእዩሆሙ፡ መላእክት፡ አውላደ፡ ሰማይ፡ ወሐየው፡ ሎሙ፡ ወይቤሉ፡ አህዱ፡ ለአህዱ፡ ንዕዳው፡ ሎነ፡ አንስትያ፡ እምእውላደ፡ ሰብእ፡ እመ፡ ወንውልድ፡ ሎነ፡ እምበእንቲአሆን።","And the angels, the children of the heaven, saw and lusted after them, and said to one another: Come, let us choose us wives from among the children of men and beget us children.")
vs(6,3,"ወይቤሎሙ፡ ሰምያዛ፡ ዘልዑሎሙ፡ ካልእ፡ እንዘ፡ ባሕትቲይአ፡ እንገብር፡ ዘከምዘ፡ ወእምአውረድ፡ እምዘ፡ ግብር፡ ወንእሰው፡ ኵሎነ፡ በምክዓት።","And Semjaza, who was their leader, said unto them: I fear ye will not indeed agree to do this deed, and I alone shall have to pay the penalty of a great sin.")
vs(6,4,"ወአውሥእው፡ ኵሎሙ፡ ወይቤሎ፡ ንማሐል፡ ኵሎነ፡ በመሐላ፡ ወእምንአውርድ፡ እምዘ፡ ግብር፡ እስከ፡ ዘንፈጽም።","And they all answered him and said: Let us all swear an oath, and all bind ourselves by mutual imprecations not to abandon this plan but to do this thing.")
vs(6,5,"ወእምኵሎሙ፡ ማሐሉ፡ ባሕትቲይአ፡ ወትጋባእው፡ ኵሎሙ፡ በምክዓት፡ ወይትማሐሉ፡ በእንተው።","Then sware they all together and bound themselves by mutual imprecations upon it.")
vs(6,6,"ወእምእሎሙ፡ መእት፡ ወዐሠርት፡ ዘወረዱ፡ በከውኢያ፡ ዘሄርሞን፡ ዲቤ፡ ደብረ፡ ዘይቤሎ፡ ጠውር፡ አርድዮስ።","And they were in all two hundred; who descended in the days of Jared on the summit of Mount Hermon, and they called it Mount Hermon, because they had sworn and bound themselves by mutual imprecations upon it.")
vs(6,7,"ወእልኩ፡ አስማቲሆሙ፡ ሰምያዛ፡ ወአርአክይብ፡ ወራምእል፡ ወኮካብእል፡ ወታምእል፡ ወራምእል፡ ወዳንእል፡ ወእዘቄእል፡ ወባራቄያል፡ ወአሳእል፡ አርማሮስ፡ ወበጠርእል፡ ወአናንእል፡ ወዘቄእል፡ ወሳምሳቤል፡ ወሸጢር፡ ወቱረእል፡ ወዩምያእል፡ ወአራዝያል።","And these are the names of their leaders: Samlazaz, their leader, Araklba, Rameel, Kokablel, Tamlel, Ramlel, Danel, Ezeqeel, Baraqijal, Asael, Armaros, Batarel, Ananel, Zaqiel, Samsapeel, Satarel, Turel, Jomjael, Sariel.")
vs(6,8,"እልኩ፡ አስማቲሆሙ፡፡ ለዐሠርት፡ እምእሎሙ፡ መእት፡ ወእምእሎሙ፡ ዐሠርት፡ ዘእልኩ፡ አሥራት፡ ዘእልኩ።","These are their chiefs of tens.")

# Chapter 7 (6 verses)
ch(7,"Chapter 7")
vs(7,1,"ወእምኵሎሙ፡ ናሥእው፡ ሎሙ፡ አንስትያ፡ ወእምወለዱ፡ ሎሙ፡ ረሲዓነ፡ ዐበይት፡ እለ፡ አብእሉ፡ እምብስት፡ እምብስት፡ እመዛጀ።","And all the others together with them took unto themselves wives, and each chose for himself one, and they began to go in unto them and to defile themselves with them.")
vs(7,2,"ወእምመሐሩሆሙ፡ ሚዝካን፡ ወስናይ፡ ወዕዐኑ፡ ወመሰርያን፡ ወምድያነ፡ ወዥፅዋነ፡ ሰማየት፡ ወንጋርጋራት።","And they taught them charms and enchantments, and the cutting of roots, and made them acquainted with plants.")
vs(7,3,"ወእምጽንሳው፡ ወእምወለዱ፡ ሎሙ፡ ገባራን፡ ዐበይት፡ እልኩ፡ ዐረፈው፡ በምብላዕ፡ ስልስት፡ ምእት፡ መዛጀ።","And they became pregnant, and they bare great giants, whose height was three thousand ells.")
vs(7,4,"እልኩ፡ በልዕ፡ ኵሎ፡ ፈርየ፡ ሰብእ፡ እመ፡ እስከ፡ ዘእምቃንና፡ ሰብእ፡ እመ፡ ይመክሎሙ፡ ወረአዩ፡ ወወዐሩ፡ ዲቤ፡ ሰብእ፡ እመ።","Who consumed all the acquisitions of men. And when men could no longer sustain them, the giants turned against them and devoured mankind.")
vs(7,5,"ወእምይዕወሩ፡ ይኋጥእ፡ አዋልድ፡ ወአዓሳት፡ ወአዕያፍ፡ ወረግባን፡ እምድር።","And they began to sin against birds, and beasts, and reptiles, and fish, and to devour one another's flesh, and drink the blood.")
vs(7,6,"ወእምድር፡ በእንተዘ፡ መአዊ፡ ዲቤሆሙ።","Then the earth laid accusation against the lawless ones.")

# Chapter 8 (4 verses)
ch(8,"Chapter 8")
vs(8,1,"ወአዛዘል፡ መሐረ፡ ለሰብእ፡ እመ፡ ጠብሣነ፡ ሳዕት፡ ወአርአየ፡ ሎሙ፡ ትዕይንተ፡ ጱብዕ፡ ወዐይን፡ ወዕዲ፡ ወእምአንፃክ፡ እመ፡ አዕይንት፡ እመ፡ አንስት።","And Azazel taught men to make swords, and knives, and shields, and breastplates, and made known to them the metals of the earth and the art of working them.")
vs(8,2,"ወዕዲ፡ ወዥፅዋነ፡ ወመንክር፡ ወእፅዋነ፡ መዓነ፡ ወጵዑዋነ፡ እመ፡ መክኵል፡ ወምንክር፡ እምእይስት።","And bracelets, and ornaments, and the use of antimony, and the beautifying of the eyelids, and all kinds of costly stones, and all colouring tinctures.")
vs(8,3,"ወእምክውን፡ ረሲዕን፡ ብዙኅ፡ ወመለከ፡ ብዙኅ፡ ዲቤ፡ ምድር፡ ወሰምያዛ፡ መሐረ፡ ዕዘያት፡ ወአርአክይብ፡ መሐረ፡ ዥድመአ፡ ከወካብት፡ ወኮካብእል፡ መሐረ፡ መንገደ፡ ከወካብት፡ ወአርማሮስ፡ መሐረ፡ እሩደ፡ መንገደ፡ ወባራቄያል፡ መሐረ፡ ሰማየት፡ ወእዘቄእል፡ መሐረ፡ እምመካን፡ ዘከወካብት።","And there arose much godlessness, and they committed fornication, and they were led astray, and became corrupt in all their ways. Semjaza taught enchantments, and root-cuttings, Armaros the resolving of enchantments, Baraqijal taught astrology, Kokabel the constellations, Ezeqeel the knowledge of the clouds.")
vs(8,4,"ወእምመአዊ፡ ዐቢይ፡ ወእምዕወይ፡ እምድር፡ እስከ፡ ሰማይ።","And there was great wickedness and much debauchery, and they sinned, and all their ways were corrupt.")

# Chapter 9 (11 verses)
ch(9,"Chapter 9")
vs(9,1,"ወእምይቤሉ፡ ሚካእል፡ ወኡርያል፡ ወራፋእል፡ ወገብርእል፡ ረእዩ፡ እምምድር፡ ወእምደም፡ ዐቢይ፡ ዘይፈስስ።","And then Michael, Uriel, Raphael, and Gabriel looked down from heaven and saw much blood being shed upon the earth, and all lawlessness being wrought upon the earth.")
vs(9,2,"ወይቤሉ፡ አሕዱ፡ ለአሕዱ፡ ናሁ፡ መአውይ፡ እምድር፡ ወእምዕወይ፡ እምድር።","And they said one to another: The earth made without inhabitant cries the voice of their cryings up to the gates of heaven.")
vs(9,3,"ወእምይቤሉ፡ ለቅዱሳን፡ ዘሰማይ፡ አንትሙ፡ እግዚአብሔር፡ ዘዐላም፡ ወእምዐላም፡ ወንጉስ፡ እግዚአብሔር።","And now to you, the holy ones of heaven, the souls of men make their suit, saying, Bring our cause before the Most High.")
vs(9,4,"ወይቤሉ፡ ለእግዚአብሔር፡ አንተ፡ እግዚአብሔር፡ እምእግዚአብሔር፡ ወእምእግዚአብሔር፡ ወአንተ፡ ንጉሥ፡ ዘንጉሳን፡ ወቅዱስ፡ ዘቅዱሳን፡ ወዐቢይ፡ ዘዐላም።","And they said to the Lord of the ages: Lord of lords, God of gods, King of kings, and God of the ages.")
vs(9,5,"መንበረ፡ ዕዘካ፡ እምለዐላም፡ ወእምይንበር፡ ወኵሎ፡ ይገብር፡ ወበዕዐካ፡ ይንበር፡ ወእምይትከወል፡ እምእንተ።","The throne of Thy glory standeth unto all the generations of the ages, and Thy name holy and glorious and blessed unto all the ages!")
vs(9,6,"አንተ፡ ገበርከ፡ ኵሎ፡ ወኵሎ፡ ትከውን፡ ወትሬኢ፡ ኵሎ፡ ወእምይትከወል፡ እምእንተ፡ ወኵሎ፡ እስከ፡ ዐላም፡ ዐላም።","Thou hast made all things, and power over all things hast Thou: and all things are naked and open in Thy sight, and Thou seest all things, and nothing can hide itself from Thee.")
vs(9,7,"ትሬኢ፡ ዘገበረ፡ አዛዘል፡ እምመሐረ፡ ኵሎ፡ ረሲዕን፡ ወእምከሰተ፡ ሚስጢራነ፡ ዘዐላም፡ ወእምክሠትከ፡ ኵሎ፡ ዘሰማይ።","Thou seest what Azazel hath done, who hath taught all unrighteousness on earth and revealed the eternal secrets which were preserved in heaven.")
vs(9,8,"ወሰምያዛ፡ ዘመሐረ፡ መንገደ፡ እይ፡ ዐዓሉ፡ ሰልጣን።","And Semjaza, to whom Thou hast given authority to bear rule over his associates.")
vs(9,9,"ወእምመጽእው፡ ኋቤ፡ አውላደ፡ ምድር፡ ወእምዐወዩ፡ በዐወዥ፡ ገባራን።","And they have gone to the daughters of men upon the earth, and have slept with the women, and have defiled themselves with them.")
vs(9,10,"ወእምአይአሆሙ፡ ኋጥኣት፡ እምዕኑ፡ ወእምወለዱ፡ ሎሙ፡ ገባራን፡ ወእምአርአዩ፡ ሎሙ፡ ኵሎ፡ ኋጥኣት።","And have revealed to them all kinds of sins. And the women have borne giants, and the whole earth has thereby been filled with blood and unrighteousness.")
vs(9,11,"ወናሁ፡ ነፍሳት፡ ዘሞቱ፡ እምመአዊ፡ ወእምዕወይ፡ እስከ፡ አንቃጻ፡ ሰማይ፡ ወምድር፡ እምእፅዋነአ፡ ትገብር።","And now, behold, the souls of those who have died are crying and making their suit to the gates of heaven, and their lamentations have ascended: and they cannot cease because of the lawless deeds which are wrought on the earth.")

# Chapter 10 (22 verses)
ch(10,"Chapter 10")
vs(10,1,"ወእምይቤ፡ ዐቢይ፡ ወእምገብርእ፡ ለኡርያል፡ አንተ፡ ሁር፡ ወብል፡ ላመክ።","Then said the Most High, the Holy and Great One spake, and sent Uriel to the son of Lamech.")
vs(10,2,"ወይቤሎ፡ ሁር፡ ወብል፡ ላመክ፡ ወብሎ፡ መዓረግ፡ ናይከ፡ ወብሎ፡ እምአውጨ፡ ዘእምይመጽእ፡ እምይጠፍእ፡ ኵሎ፡ ዘዲቤ፡ ምድር፡ ወአውድእ፡ ወአክርእሎ፡ ወዘእምነ፡ ዥድመአ፡ ይመጽእ፡ ወይዐቢይ፡ መያ፡ ይወጽእ።","And say unto him: tell him in my name, Hide thyself! and reveal to him the end that is approaching: that the whole earth will be destroyed, and a deluge is about to come upon the whole earth, and will destroy all that is on it.")
vs(10,3,"ወእምአይአሆ፡ እምእመክንይ፡ ይአጥርይ፡ ነፍሱ፡ እምዐርእ፡ ዘዝርዕ፡ እምይንበር፡ እምእንተው።","And now instruct him that he may escape and his seed may be preserved for all the generations of the world.")
vs(10,4,"ወካዕ፡ ይቤ፡ እግዚአብሔር፡ ለራፋእል፡ ሁር፡ አስር፡ አዛዘል፡ እድይሁ፡ ወእገሑ፡ ወዕደደሆ፡ በበደው፡ ዘይካውን፡ በምድረ፡ ዘዱዳእል።","And again the Lord said to Raphael: Bind Azazel hand and foot, and cast him into the darkness: and make an opening in the desert, which is in Dudael, and cast him therein.")
vs(10,5,"ወዕደዱ፡ ዲቤእሁ፡ አዕብን፡ አፅኁት፡ ወዥዘያን፡ ወዕደሆ፡ ዲቤ፡ ጽልማት፡ በእንተዘ፡ ይንበር፡ ዝየ፡ እምእንተዘ፡ ይኪድ።","And place upon him rough and jagged rocks, and cover him with darkness, and let him abide there for ever, and cover his face that he may not see light.")
vs(10,6,"ወበዐቢይ፡ ዐላም፡ ይመከር፡ ደይን፡ ወይዕደዱ፡ በእሳት።","And on the day of the great judgement he shall be cast into the fire.")
vs(10,7,"ወይገብር፡ ምድረ፡ እንተ፡ ዘገብረ፡ አዛዘል፡ ረሲዕን፡ ወእምክሠትከ፡ ኵሎ፡ መዛዕ፡ ዘዲቤ፡ ምድር።","And heal the earth which the angels have corrupted, and proclaim the healing of the earth, that they may heal the plague.")
vs(10,8,"እምእይጠፍእ፡ ኵሎ፡ አውላደ፡ ሰብእ፡ እመ፡ በመዛዕ፡ እመ፡ ዘመሐሩ፡ ዐቃብያን፡ ለአውላደ፡ ሰብእ፡ እመ።","And all the children of men may not perish through all the secret things that the Watchers have disclosed and have taught their sons.")
vs(10,9,"ወኵልእ፡ ምድር፡ ፈሰደት፡ በሚዝካን፡ ወመንገደ፡ እምዕዐኑ፡ ወእምስናይ፡ ወእምክውን፡ ረሲዕን፡ ኵሎሙ፡ በሓ።","And the whole earth has been corrupted through the works that were taught by Azazel: to him ascribe all sin.")
vs(10,10,"ወገብርእል፡ ቤ፡ እግዚአብሔር፡ ለሰምያዛ፡ ወለኵሎሙ፡ መሐር፡ ሎሙ፡ እምእወለዱ፡ ለእንተዘ፡ ይገድሉ፡ አሕዱ፡ አሕዱ።","And to Gabriel said the Lord: Proceed against the bastards and the reprobates, and against the children of fornication: and destroy the children of the Watchers from amongst men. Send them one against the other.")
vs(10,11,"ወንእሥእሆሙ፡ ይጠፍእው፡ አሕዱ፡ አሕዱ፡ በመካን፡ ወበመጠፍእ፡ እምይሐያው፡ መካን፡ እምይገድሉ።","And let them destroy one another in battle: for length of days shall they not have.")
